### ISSUE TITLE
Segmentation fault with "sgd" solver

### ISSUE THREAD

**Issue by dselivanov** [ibayer/fastFM-core#16]
Thanks for your work - FastFM is amazing (and in future I want to contribute to your project and create R bindings).
Currently however I'm using CLI interface. Both "mcmc" and "als" solvers work fine on my dataset, but "sgd" produces: "Segmentation fault (core dumped)". [Here are files](https://drive.google.com/open?id=0By2BzucAKDF5dUxSckI0b3laRGc) to reproduce error. I use following command:
```
./bin/fastfm train_1e6.svmlight train_1e6.svmlight --task='classification' --n-iter=10 --solver='sgd' --rank 5
```

**Comment by ibayer** [comment]
Glad you like it.

I'm very interested in R bindings myself let me know if you run into issues I might be able
to help you with.

Please check if you still get the error with a smaller step-size.

**Comment by dselivanov** [comment]
Tried with as small as `--step-size==0.00000001` - still "Segmentation fault".

**Comment by ibayer** [comment]
Okay, I'll investigate this issue sometime next week.
I never use the sgd solver myself. I think als/mcmc is faster and easier to tune.

**Comment by ibayer** [comment]
@dselivanov 
Can you confirm that the issue is now fixed?

**Comment by dselivanov** [comment]
In trip at the moment. Will be able to test in next 2-3 days.

10 дек. 2016 г. 7:41 ПП пользователь "ibayer" <notifications@github.com>
написал:

**Comment by dselivanov** [comment]
Thanks for quick fix. Works fine now.
