### ISSUE TITLE
other solvers for BPR loss?

### ISSUE THREAD

**Issue by dongguosheng** [ibayer/fastFM-core#18]
Is there any reason that only sgd solver is supported for BPR loss ? ALS or MCMC is not applicable for pairwise loss ?

**Comment by ibayer** [comment]
BPR loss can only be optimized with SGD for any reasonably sized data. Implicit regularization [0] is an ALS / CD alternative for ranking, I might include this algorithm in the future.

[0][ A Generic Coordinate Descent Framework for Learning from Implicit Feedback](https://arxiv.org/pdf/1611.04666)

**Comment by dongguosheng** [comment]
Got it, thanks for the quick reply!
